#pgbench -i -s: 1000 1027s
#pgbench -T 300 -c10 -j20 -r: 347 tps
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-test-cluster1
spec:
  teamId: "acid-test"
  numberOfInstances: 3
  users:
    zalando:
    - superuser
    - createdb
  databases:
    testdb: zalando
  postgresql:
    version: "13"
  volume:
    size: 1Gi
    storageClass: nfs-csi
  spiloRunAsUser: 101
  spiloRunAsGroup: 103
  spiloFSGroup: 103
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
  patroni:
    initdb:
      encoding: "UTF8"
      locale: "en_US.UTF-8"
      data-checksums: "true"
