# pgbench -i -s 1000: 244.59 s
# pgbench -T 300 -c10 -j20 -r: 10567 tps
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-test-cluster1
spec:
  teamId: "acid-test"
  numberOfInstances: 1
  users:
    zalando:
    - superuser
    - createdb
  databases:
    testdb: zalando
  postgresql:
    version: "13"
  spiloRunAsUser: 101
  spiloRunAsGroup: 103
  spiloFSGroup: 103
  resources:
    requests:
      cpu: "16"
      memory: 32Gi
    limits:
      cpu: "16"
      memory: 32Gi
  patroni:
    initdb:
      encoding: "UTF8"
      locale: "en_US.UTF-8"
      data-checksums: "true"
  volume:
    size: 1Gi
    storageClass: nfs-csi
  additionalVolumes:
  - name: data
    mountPath: /home/postgres/pgdata/pgroot
    targetContainers:
    - all
    volumeSource:
      emptyDir: 
        sizeLimit: 100Gi
