#pgbench -i -s: 1000 9m47.732s
#pgbench -T 300 -c10 -j20 -r: 602.5 tps
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-test-cluster  ## name of our cluster
spec:
  teamId: "acid-test"
  numberOfInstances: 1     ## single instance
  users:
    zalando:               ## create user to db
    - superuser
    - createdb
  databases:            
    testdb: zalando        ## create db 'testdb' and add access to 'zalando' user
  postgresql:
    version: "13"          ## deploy postgres version 13
  volume:
    size: 1Gi            
    storageClass: nfs-csi  ## use nfs-csi class for backend storage
  spiloRunAsUser: 101      ## security context for db deployment
  spiloRunAsGroup: 103
  spiloFSGroup: 103
  resources:               ## give some resources
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
  patroni:
    initdb:                ## setup db for utf-8
      encoding: "UTF8"
      locale: "en_US.UTF-8"
      data-checksums: "true"
