theme: jekyll-text-theme

text_skin: default
highlight_theme: tomorrow-night
url     : https://cerit-sc.github.io
baseurl : # dunno
title   : CERIT-SC Kubernetes Docs
description: > # this means to ignore newlines
  CERIT-SC Kubernetes docs

lang: en
timezone: CZ

author:
  type      : "organization"
  name      : CERIT-SC

repository: CERIT-SC/kube-docs
repository_tree: gh-pages

paths:
  root    : # title link url, "/" (default)
  home    : # home layout url, "/" (default)
  archive : # "/archive.html" (default)
  rss     : # "/feed.xml" (default)

excerpt_separator: <!--more-->

license: CC-BY-NC-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

toc:
  selectors: # "h1,h2,h3" (default)

## => Markdown Enhancements
##############################
mathjax: # false (default), true
mathjax_autoNumber: # false (default), true
mermaid: # false (default), true
chart: # false (default), true

## => Search
##############################
search:
  provider: false # "default" (default), false, "google", "custom"

  ## Google Custom Search Engine
  google:
    custom_search_engine_id: # Google Custom Search Engine ID

## => Build
##############################
markdown    : kramdown
highlighter : rouge
permalink   : date

exclude:
  - CHANGELOG.md
  - HOW_TO_RELEASE.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: "docs"
      type: posts
    values:
      layout: article
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
